apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadduak3550-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadduak3550-tenant-component
    app.kubernetes.io/part-of: loadduak3550-tenant-app
  name: loadduak3550-tenant-component
  namespace: loadduak3550-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadduak3550-tenant-component
    weight: null
status: {}
